version: '3.7'

services:

  php:
    container_name: ieducar-php
    build: docker/php
    links:
      - postgres
      - redis
    environment:
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      DB_HOST: postgres
      PGPASSWORD: ieducar
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ../i-educar-reports-package:/var/www/ieducar/packages/portabilis/i-educar-reports-package
    entrypoint: ["sh", "/usr/local/bin/entrypoint.sh"]

  nginx:
    container_name: ieducar-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - php
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx:/etc/nginx/conf.d/      

  postgres:
    container_name: ieducar-postgres
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ieducar
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    volumes:
      - postgres:/var/lib/postgresql/data
      - ../backup:/backup
    command: >
      postgres
      -c logging_collector=off
      -c log_statement=all
      -c log_destination=stderr
      -c log_min_duration_statement=0

  redis:
    container_name: ieducar-redis
    image: redis:alpine
    restart: always

volumes:
    postgres:
