INSERT INTO cadastro.deficiencia VALUES (8, 'Deficiência Intelectual', 7, false);
INSERT INTO cadastro.deficiencia VALUES (10, 'Transtorno do espectro autista', 25, false);
INSERT INTO cadastro.deficiencia VALUES (14, 'Altas Habilidades/Superdotação', 13, false);
INSERT INTO cadastro.deficiencia VALUES (2, 'Cegueira', 1, false);
INSERT INTO cadastro.deficiencia VALUES (3, 'Baixa Visão', 2, false);
INSERT INTO cadastro.deficiencia VALUES (4, 'Surdez', 3, false);
INSERT INTO cadastro.deficiencia VALUES (5, 'Deficiência Auditiva', 4, false);
INSERT INTO cadastro.deficiencia VALUES (6, 'Surdocegueira', 5, false);
INSERT INTO cadastro.deficiencia VALUES (7, 'Deficiência Física', 6, false);
INSERT INTO cadastro.deficiencia VALUES (9, 'Deficiência Múltipla', 8, false);
