FROM nginx:1.28-alpine

WORKDIR /var/www/ieducar

RUN apk add --no-cache gettext

COPY . /var/www/ieducar

COPY docker/nginx/conf.d/nginx.conf /etc/nginx/conf.d/nginx.conf
COPY docker/nginx/templates/default.template.conf /etc/nginx/templates/default.template.conf
COPY docker/nginx/entrypoint.prod.sh /usr/local/bin/entrypoint.prod.sh

RUN chmod +x /usr/local/bin/entrypoint.prod.sh

ENTRYPOINT ["sh", "/usr/local/bin/entrypoint.prod.sh"]
